In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
#Dimension of the array.

print(arr.ndim)

2


In [5]:
#Shape of the array.

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]])
print(b,"\n")

[[20 21 22]
 [25 26 27]
 [30 31 32]] 



In [7]:
b.dtype

dtype('int32')

In [8]:
b.itemsize

4

In [9]:
b.size

9

In [10]:
b.shape

(3, 3)

In [12]:
b = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

float64 

8


In [13]:
z = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex64)
t = np.array([[20,21,22],[25,26,27],[30,31,32]], dtype=np.complex128)
print(z,"\n")
print(z.dtype,"\n")
print(z.itemsize,"\n")
print(t,"\n")
print(t.dtype,"\n")
print(t.itemsize,"\n")

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex64 

8 

[[20.+0.j 21.+0.j 22.+0.j]
 [25.+0.j 26.+0.j 27.+0.j]
 [30.+0.j 31.+0.j 32.+0.j]] 

complex128 

16 



In [14]:
#Sum value along a specified axis.
print(np.sum(b))

234.0


In [15]:
#Sum along a specified axis.
print(b,"\n")
print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[75. 78. 81.]
[63. 78. 93.]


In [16]:
#Minimum value.
print(b,"\n")
print(np.amin(b))
print(np.amin(b,axis=0))
print(np.amin(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

20.0
[20. 21. 22.]
[20. 25. 30.]


In [17]:
#Maximum value.
print(b,"\n")
print(np.amax(b))
print(np.amax(b,axis=0))
print(np.amax(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

32.0
[30. 31. 32.]
[22. 27. 32.]


In [18]:
#Mean
print(b,"\n")
print(np.mean(b))
print(np.mean(b,axis=0))
print(np.mean(b,axis=1))
print(type(b))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

26.0
[25. 26. 27.]
[21. 26. 31.]
<class 'numpy.ndarray'>


In [19]:
#Standard Deviation
print(b,"\n")
print(np.std(b))
print(np.std(b,axis=0))
print(np.std(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

4.163331998932265
[4.0824829 4.0824829 4.0824829]
[0.81649658 0.81649658 0.81649658]


In [20]:
#Variance
print(b,"\n")
print(np.var(b))
print(np.var(b,axis=0))
print(np.var(b,axis=1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

17.333333333333332
[16.66666667 16.66666667 16.66666667]
[0.66666667 0.66666667 0.66666667]


In [21]:
#Weighted Average
print(np.average(b))

26.0


In [22]:
c = np.array([2,4,6,1,3,5,8,10,12,7,9,11])
print(c)

[ 2  4  6  1  3  5  8 10 12  7  9 11]


In [24]:
weight = np.array([0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5,0.25,0.5])
print(weight)

[0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5  0.25 0.5 ]


In [25]:
print(np.average(c,weights = weight))

6.444444444444445


In [26]:
#Peak to peak.
print(b,"\n")
print(c,"\n")
print(np.ptp(c,0))
print(np.ptp(b,0))
print(np.ptp(b,1))

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

[ 2  4  6  1  3  5  8 10 12  7  9 11] 

11
[10. 10. 10.]
[2. 2. 2.]


In [27]:
print(b,"\n")
print(b.shape,"\n")
#print(b.reshape(2,4),"\n")
print(b)

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]] 

(3, 3) 

[[20. 21. 22.]
 [25. 26. 27.]
 [30. 31. 32.]]


In [28]:
r = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print(r,"\n")
print(np.shape(r))
print(r.reshape(4,3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

(3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
#2D Array
l=np.array([[23,25,27,29],[43,45,47,49],[62,66,68,70]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 

29 

47 

70 

25 

[25 45] 

[62 66 68 70] 

[62 66] 



In [31]:
d=np.arange(12).reshape(3,4)
print(d,"\n")
f=np.arange(12,24).reshape(3,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
print(d,"\n")
print(f,"\n")
print(np.hstack((d,f)),"\n")
print(np.hstack((f,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 

[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]] 



In [34]:
print(d,"\n")
print(f,"\n")
print(np.vstack((d,f)),"\n")
print(np.vstack((f,d)),"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



In [35]:
from numpy import random
x=random.randint(100)
print(x)

57
